apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      automountServiceAccountToken: false
      containers:
        - name: backend
          image: employee-backend:latest
          imagePullPolicy: Never
          env:
            - name: DB_HOST
              value: db
            - name: DB_NAME
              value: employeedb
            - name: DB_USER
              value: empuser
            - name: DB_PASSWORD
              value: emppass
          ports:
            - containerPort: 3000
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 250m
              memory: 256Mi
          # CORRECCIÓN: se evita escalada de privilegios y ejecución como root
          securityContext:
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            runAsUser: 1000
            capabilities:
              drop:
                - ALL